### ISSUE TITLE
The dispatcher.sh script is not executable

### ISSUE THREAD

**Issue by seeroush** [adityakar/workflow-dispatcher#1]
I attempted to use the action from the marketplace, but ran into the following error:

```
/home/runner/work/_temp/f003fcb6-b30c-4d39-ac8e-28b0bdeca62d.sh: line 1: /home/runner/work/_actions/adityakar/workflow-dispatcher/v1.0/dispatcher.sh: Permission denied
```

It looks as if the shell script needs to have execute permissions before it's able to run. Here's my sample action:

```
name: Test Dispatcher
on: push
jobs:
  CI:
    runs-on: ubuntu-latest 
    timeout-minutes: 10
      - name: Start Dispatch
        uses: adityakar/workflow-dispatcher@v1.0
        with:
          owner: my-org
          repo: my_repo
          token: ${{ secrets.GITHUB_TOKEN }}
          event_type: my_event
          client_payload: '{"var1": "test, test, test!"}'
          wait_time: 5
          max_time: 180
```
